[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pers_cohort_query"
version = "0.1.0"
description = "Personalized cohort builder for All of Us"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]

dependencies = [
    "numpy",
    "pandas",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit",
    "pytest",
]
