---
title: "pers_cohort_query Development Notes"
format:
  revealjs:
    theme: [dracula]
    incremental: false
    transition: slide
    slide-number: true
---

## pers_cohort_query modules {.smaller}

- **module: extract** lab values and cohorts from a database
  - *module to be developed next*
- **module: integrate** lab values and cohorts to compute personalized cohort shifts
  - *only module currently developed & reviewed*
- **module: summarize** shifts at personalize and population level (?)
  - *skeleton to be added next, then hold off until after extract module*

## integrate module review {.smaller}

- **done:**
  - switch all to TSV
  - fix bugs (custom column names, edge cases)
  - comment why instead of what, limit docstrings
  - refactor to separate loading and validation
  - factor validation patterns to functions
  - separate modules into io.py, etc.
  - enforce lab values numeric and finite
  - return NaN for zero variance instead of throwing error
  - small optimizations while keeping pandas

## integrate module review {.smaller}

- **to do:**
  - output more than just shift peak (separate PR)

## integrate module review {.smaller}

- **to discuss:**
  - should missing values throw an error?
  - should KDE shift be used for all inputs?
  - how to correctly account for the longitudinal data?
  - gaurd against one extreme value shifting entire cohort by a constant?
  - should exact duplicate rows be allowed in input? (currently yes)
  - does GenoSiS require same cohort length, pad, or fail?

## integrate module review {.smaller}

- **maybe later:**
  - export public functions for use
  - consider conda-lock or uv for true reproducibility
  - performance optimization if necessary (KDE with Fourier transform, etc.)
  - implement pipeline as a Snakemake workflow
  - consider swtiching Pandas for Polars
